# true: up/down arrows in "module beheren"
sequence_module: false
gui_image_bg: false
header_text: SansSerif 36 Bold
#221, 238, 255
main_background: #FFFFFF
main_foreground: #314770
fi_logo_location: resources/fi.gif
wisweb_logo_small_location: resources/numworx.png
wisweb_logo_location: resources/wisweb.gif

header_color: #314770
#221, 238, 255
cell_background = #DDEEFF
gui_image_welcome = resources/EPN-welkom.jpg
gui_image_sco = resources/EPN-sco.png
gui_image_course = resources/EPN-course.png

gui_iconized = true
default_iconized = true;
gui_bgimage_icon = resources/iconized-bgimage.png
gui_9patch_icon = 0 1 1 80 480 500
gui_insets_icon = 18 6 8 6

gui_bgimage_menu = resources/menu-bgimage.png
gui_9patch_menu = 20 140 159 80 480 500
gui_insets_menu = 18 6 8 6

gui_bgimage_sco = resources/sco-bgimage.png
gui_9patch_sco = 59 600 643 80 480 500
gui_insets_tree = 18 6 8 6
gui_insets_sco  = 4 4 0 0

deployVariant =

player=/dwo/apps/player.html
#profiel 77
#player_base=https://cdn.dwo.nl/dwo/apps/
#de default is van noordhoff.
player_base=https://cdplogica.toegang.nu/noordhoff/vo/fi/dwo/2017_v1-PL/
#plantijn profiel:
#player_base=https://scoodleso.blob.core.windows.net/dwo-logica/plantyn/

fonts=resources/fonts/Ubuntu-R.ttf,\
	resources/fonts/Ubuntu-RI.ttf,\
	resources/fonts/Ubuntu-B.ttf,\
	resources/fonts/Ubuntu-BI.ttf,\
	resources/fonts/Omega_0.ttf
