gui_image_bg: true
gui_iconized: false
main_background: #FFFFFF
cell_background: #FFFFFF
gui_image_welcome = resources/UU-jcu-welkom.png
gui_image_sco = resources/UU-jcu-sco.png
gui_image_course = resources/UU-jcu-course.png
