# 255,255,200
main_background: -56
cell_background: -56
header_text: SansSerif 33 Bold
fi_logo_location: resources/rekenweb.png
wisweb_logo_small_location: resources/rekenweb.png
wisweb_logo_location: resources/rekenweb.png

