gui_image_bg: true
gui_iconized: true
main_background: #FFFFFF
cell_background: #FFFFFF
gui_image_welcome = resources/UU-bio-welkom.png
gui_image_sco = resources/UU-bio-sco.png
gui_image_course = resources/UU-bio-course.png
