gui_image_bg: true
gui_iconized: true
main_background: #FFFFFF
cell_background: #FFFFFF
gui_image_welcome = resources/MW-welkom.png
gui_image_sco = resources/MW-tf-sco.png
gui_image_course = resources/MW-tf-course.png
deployVariant=MW
player = /dwo/apps/noordhoff/player.html
student_player = /mw/tf/leerling/
