gui_image_bg: true
gui_iconized: true
default_iconized: true
main_background: #FFFFFF
cell_background: #FFFFFF
gui_image_welcome = resources/DSOUU-dwo-welkom.png
gui_image_sco = resources/DSOUU-dwo-sco.png
gui_image_course = resources/DSOUU-dwo-course.png
gui_bgimage_icon = resources/DSOiconized-bgimage.png
gui_bgimage_menu = resources/DSOmenu-bgimage.png
gui_bgimage_sco = resources/DSOsco-bgimage.png

