gui_image_bg: true
gui_iconized: true
main_background: #FFFFFF
cell_background: #FFFFFF
gui_image_welcome = resources/EPN-welkom.jpg
gui_image_sco = resources/EPN-sco.png
gui_image_course = resources/EPN-course.png
deployVariant=GR
player = /dwo/apps/noordhoff/player.html
student_player = /gr/ob/leerling/
