gui_image_bg: true
gui_iconized: true
default_iconized: true
main_background: #FFFFFF
cell_background: #FFFFFF
gui_image_welcome = resources/welkom_wisse.png
gui_image_sco = resources/bg_sco_wisse.png
gui_image_course = resources/course_wisse.png
gui_bgimage_icon = resources/iconized_wisse.png
gui_bgimage_menu = resources/menu_wisse.png
gui_bgimage_sco = resources/sco_wisse.png
student_player=/rekenwise/leerling/
