gui_image_bg: true
gui_iconized: true
default_iconized: true
main_background: #FFFFFF
cell_background: #FFFFFF
gui_image_welcome = resources/UU-dwo-en-welkom.png
gui_image_sco = resources/UU-dwo-en-sco.png
gui_image_course = resources/UU-dwo-en-course.png
