gui_image_bg: true
gui_iconized: true
default_iconized: true
main_background: #FFFFFF
cell_background: #FFFFFF
gui_image_welcome = resources/UU-geo-welkom.png
gui_image_sco = resources/UU-geo-sco.png
gui_image_course = resources/UU-geo-course.png
