number: 10
school.1: 0
access.1: true
school.2: 1115
access.2: true
school.3: 1116
access.3: true
school.4: 1117
access.4: true
school.5: 1137
access.5: true
school.6: 1140
access.6: true
school.7: 1141
access.7: true
school.8: 1142
access.8: true
school.9: 1202
access.9: true
school.10: 1203
access.10: true
